baseurl = "http://blog.bhavenger.com/"
languageCode = "en-us"
title = "Techologies 101"
MetaDataFormat = "toml"
theme = "blackburn"
paginate = 5
PaginatePath = "/"
canonifyurls = true

[author]
name = "Dmitriy Zaitsev"

[indexes]
tag = "tags"
topic = "topics"

[permalinks]
# Permalink format for pages.
page = "/:filename/"
# Permalink format for blog posts.
post = "/:year/:month/:filename/"

[params]
highlightjs = "solarized-dark"
# Footer; Markdown accepted here.
footer = "Copyright 2016 &copy; Dmitriy Zaitsev"
subtitle = "Keep It Simple Stupid"
brand = "bhavenger"
# Description and keywords for <meta> tags.
# Remember to set this for your main page.
# This will be overridden by whatever is set by the page or post,
# defined by `description` and `keywords` variables in the front matter
# of the markdown file.
description = "Блог о технологиях и обучении"
keywords = "devops, it, techonologies, docker, aws"
googleAnalytics = "UA-74400829-1"
disqus = "techologies101"

[social]
email = "mailto:bhavenger@gmail.com"
github = "bhavenger"
#bitbucket = "url-to-your-bitbucket"
twitter = "bhavenger"
stackoverflow = "2677712/bhavenger"
linkedin = "bhavenger"
facebook = "bhavenger"

[menu]
# Menu for the nav bar.
# There must always be one item present (e.g. home).
[[menu.main]]
identifier = "home"
name       = "home"
url        = "/"
weight     = 0

[[menu.main]]
identifier = "about"
name       = "about"
url        = "/about/"
weight     = 1
