baseurl = "http://blog.bhavenger.com"
languageCode = "en-us"
title = "Techologies 101"

MetaDataFormat = "toml"
theme = "slender"
paginate = 5
PaginatePath = "/"

[author]
name = "Dmitriy Zaitsev"

[permalinks]

# Permalink format for pages.
page = "/:filename/"

# Permalink format for blog posts.
post = "/:year/:month/:filename/"

[params]

# Change the color scheme of Slender.
# See above for preview and list of color schemes.
colorscheme = "white"

# Tagline; HTML accepted here. Keep it concise.
tagline = "Keep It Simple Stupid"

# Footer; Markdown accepted here.
footer = "Copyright 2015 &copy; Dmitriy Zaitsev"

# Description and keywords for <meta> tags.
# Remember to set this for your main page.
# This will be overridden by whatever is set by the page or post,
# defined by `description` and `keywords` variables in the front matter
# of the markdown file.
description = "Блог о технологиях и обучении"
keywords = "devops, it, techonologies, docker, aws"

# Social links, must be full URLs (e.g. https://github.com/CrimsonRay/).
# Remove, comment, or leave blank any field to leave them out.
email = "mailto:bhavenger@gmail.com"
github = "https://github.com/bhavenger"
#bitbucket = "url-to-your-bitbucket"
twitter = "https://twitter.com/bhavenger"
stackoverflow = "http://stackoverflow.com/users/2677712/bhavenger"
linkedin = "https://www.linkedin.com/in/bhavenger"
facebook = "https://www.facebook.com/bhavenger"

# Google Analytics
# Remove, comment, or leave it blank if you don't have one.
ganalytics = "UA-74400829-1"

[menu]

# Menu for the nav bar.
# There must always be one item present (e.g. home).
[[menu.main]]
identifier = "home"
name       = "home"
url        = "/"
weight     = 0

[[menu.main]]
identifier = "about"
name       = "about"
url        = "/about/"
weight     = 1
